# Student Success & Academic Outcomes Analysis

## 1. Data Preparation and Validation

This section profiles the raw student dataset, evaluates data quality, and prepares the data for downstream SQL, statistical, and visualization analysis.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
os.listdir()

['Untitled Folder',
 'Lakendra_Baines Resume.pdf',
 'Leading Causes of Death.csv',
 'Interview Questions.docx',
 'salesdb_portfolio.sqlite',
 'Baines_Assign1 - Jupyter Notebook.pdf',
 'Manifestation Home Healthcare.pdf',
 'ARD Screenshot 12',
 'HR-Employee-Attrition.csv',
 'LakendraB Resume.pdf',
 'Jerome JB Baines.docx',
 'Untitled68.ipynb',
 'ARD Screenshot 15',
 'Tyrone Transcript from Sterling.jpg',
 'CertificateOfCompletion_R for Data Science Analysis and Visualization (1).pdf',
 'new_finance .csv',
 'Tyrone Social Security Card.jpg',
 'Untitled55.ipynb',
 'Untitled10.ipynb',
 'Jeremiah Baines BC.pdf',
 'Milestone 2.ipynb',
 'System Analysis and Design - Mid Term.docx',
 'Untitled7.ipynb',
 'HR Anaytics Dashboard.pdf',
 'Developing Communication and Training Skills.docx',
 'P02_07 6.19.2023.xlsx',
 'Validation Request - Portfolio Credit .docx',
 '2025-2026 Quarter 1 Progress Report.pdf',
 'LakendraBainesResume.docx',
 '.config',
 'Untitled34.ipynb',
 'Sales Performance Dashboard.twb',
 'Music',
 'Hw1Project 3.java',
 'Creating Incident Awareness Training - Quiz.docx',
 'Campus Dining Services Information System.pdf',
 'Power BI Dashboard.pdf',
 'NIST’s Cybersecurity Framework Project.docx',
 'treeml.xml',
 'Project Phase 5.docx',
 'P10_16 6.24.2023.xlsx',
 'Healthcare.ipynb',
 'Jerome Class A.jpg',
 'JB Cover_Letter.docx',
 'Exam 2 CIS 5353.docx',
 'P10_28 6.26.2023.xlsx',
 'workforce_attrition_analysis.sql.sql',
 '.zprofile.pysave',
 'Enterprise_Sys_CRM_MISY_5380_Spring_2024.pdf',
 'CIS 5304 Mid-Term Exam.docx',
 'Telecommunications.docx',
 'Cover Letter.docx',
 '.condarc',
 'ARD Screenshot 22',
 'IMG_4804 4.jpg',
 'Cisco Packet Tracer 8.2.2',
 'Jazlene L. Resume.pdf',
 'Debt Validation - First Source 7.25.2023.docx',
 'Untitled36.ipynb',
 'IT Project Management Plan.docx',
 'ARD Screenshot 14',
 'Validation Request - Spire Recovery .pdf',
 '.copilot',
 'ARD Screenshot 13',
 'Jerome Baines Jr BC.pdf',
 'JB Report Card 3 2023-2024.pdf',
 'ERP_Overview_MISY_5340_Fall_2023.pdf',
 'Hospital Dashboard.png',
 'bank.csv',
 'Untitled57.ipynb',
 'Untitled12.ipynb',
 'student_success_analysis.sql',
 'Validation Request - Resurgent Capital Services 3.2025.pdf',
 'IMG_4660.jpg',
 'Untitled5.ipynb',
 '_Luke 1_45_ Journal for Sale by enchantedlove _ Redbubble_files',
 'Enhancing Information Security .docx',
 'Assignment 1.pkt',
 'P02_03 6.18.2023.xlsx',
 'Care Credit - Charge Off.docx',
 'CIS 5355 Assignment 1.ipynb',
 'Louisiana FCU - Charge Offs.docx',
 'ARD Screenshot 5.htm',
 'Lakendra Baines - Cover Letter.pdf',
 'Final Project Report..ipynb',
 'JertoriaB Resume.docx',
 'Untitled1.ipynb',
 'Lakendra Baines -.docx',
 'Order_State_Machine_Lucidchart.csv',
 'il_1588xN.583784569_s019.webp',
 'Salesdb_portfolio.sql',
 'new_finance.xls',
 'Burst Detection - 5355 Assignment 1.docx',
 'Jazlene Locander Resume .pdf',
 'CIS 5355 Week 7 Assignment .docx',
 'Technology Report.docx',
 'Debt Validation Letter - MCM 9.1.2023.docx',
 'TAMUCT_MS_Information_Systems.jpg',
 'UAB Essay.docx',
 'Untitled53.ipynb',
 'Untitled16.ipynb',
 'UAB Essay.pdf',
 'Individual Project CIS 5353.docx',
 'Validation Request - Phillips & Cohen.docx',
 'Information Systems - Lakendra Baines.docx',
 'CIS 5304 Assignment 3.docx',
 'LakendraBaines_Data_Analyst_Resume.docx',
 'CIS 5355 Assignment 4.docx',
 'Michelle_Baines.docx',
 '.DS_Store',
 'Hospital Reporting State.csv',
 'Jertoria & Tyrone Baines Withdrawal.pdf',
 'CertificateOfCompletion_Microsoft SQL Server 2022 Essential Training.pdf',
 'HW2App.java',
 'Lamar University.pdf',
 'LakendraBMBA-HRM.pdf',
 'Validation Request - LVNV Funding.docx',
 'CertificateOfCompletion_ETL in Python and SQL.pdf',
 '_Luke 1_45_ Journal for Sale by enchantedlove _ Redbubble.html',
 'new_finance .xlsx',
 'Validation Request - Transworld System.docx',
 'Final Exam Question 2.docx',
 'Validation Request - Portfolio Recoery.docx',
 'mesothelioma_bursts.csv',
 'Ashley Price _ “Write the vision and make it plain” Habakkuk 2_2-3 🙌🏾✨ Habakkuk 2_2-3 emphasizes the importance of writing down your vision and plans so... _ Instagram_files',
 'CS - Data Analyst.pdf',
 '~$ERPSim.docx',
 'SAP2.docx',
 'diabetes_sample.csv',
 '.vscode-shared',
 'Untitled32.ipynb',
 'Fax Confirmation.pdf',
 'Document_2026-07-20_124500.pdf',
 'UAB.pdf',
 'Lakendra Baines Offer for Employment (1).pdf',
 'HR background.pptx',
 'JB Report Card 4 2023-2024.pdf',
 'LakendraBaines.docx',
 'Khols - Charge Off.docx',
 'Worker Scheduling(1) 7.16.2023.xlsx',
 'CIS 5304 Final Paper Draft.docx',
 'Milestone 2.ipynb.pdf',
 '.CFUserTextEncoding',
 'First Premier - Charge Offs.docx',
 'Untitled30.ipynb',
 'Project Phase 4.docx',
 'ERPSim.docx',
 'Untitled48.ipynb',
 'Baines_Assign3 .pdf',
 'Ally Goodwill Letter.docx',
 'txu 8:11:2025.pdf',
 '<tree>.xml',
 'magic04.data',
 '6c973f9b31a6f8315507f9e0bb1921fd-p_e.jpg',
 'Cover Letter - Rising HR.pdf',
 'Hw1Project 2.java',
 'Recorded Paper Presentation.pptx',
 'Cybersecurity_Man_MISY_5325_Fall_2023.pdf',
 'Jerome Baines Reference for Kendra.docx',
 '.xonshrc',
 'A2LB.docx',
 'evolutionofai.webp',
 'Lakendra_Baines Resume.docx',
 '61vkymSEGKL._AC_UF894,1000_QL80_.jpg',
 'javac Card.java',
 'Untitled29.ipynb',
 'us_state_vaccinations.csv',
 'Jer_2911_web_940x.webp',
 'Assign_2.docx',
 'Document_2023-10-10_112926.pdf',
 'espedfile Q3 Progress Report .pdf',
 'TXU Bill .pdf',
 'Validation Request - SCS.docx',
 'Validation Request - Plaza Services.docx',
 'anaconda_projects',
 'Untitled3.ipynb',
 'Exam 1 CIS 5353.docx',
 '~$ Resume.docx',
 'Untitled51.ipynb',
 'Untitled14.ipynb',
 'Data Modeling.docx',
 'Jerome Baines Time sheet.pdf',
 'Birth Certificate.pdf',
 'depth_vs_magnitude_automatic_reviewed.html',
 'python-sales-analytics-portfolio--main.zip',
 'Assignment Grapghs.ipynb',
 'View Your Report _ TransUnion Credit Report.pdf',
 'loan_visualizations.ipynb',
 'Tyrone Baines Resume.docx',
 'hw3proj1.java',
 'Untitled.ipynb',
 'Visual Analytics Project - CIS 5355.pptx',
 'IMG_4804..pdf',
 'Lakendra Baines 9.17.2025.pdf',
 'Answer Sheet - Titanic Analysis.docx',
 'Data Dictionary.docx',
 'Untitled37.ipynb',
 'SAS 7.16.2023.docx',
 'Chantavia Baines Resume.docx',
 'espedfile Q4 Progress Report.pdf',
 '.zshrc',
 'ARD Screenshot 2.jpg',
 'Assignment 2 CIS 5304.pdf',
 'Jazlene EKG.pdf',
 'HR Data Analytics.pdf',
 'Elektra Carter.docx',
 'Validation Request - Resurgent Capital Services 3.2025.docx',
 'Information Systems - Lakendra Baines1.pdf',
 'JeromeBaines.docx',
 'CertificateOfCompletion_Learning Excel Data Analysis.pdf',
 '.packettracer',
 'Answer Sheet - Analysis Using GBI Pt2.docx',
 '458500857_18457716799036441_2449385089536922017_n.jpg',
 'hr_meme_scaring_employees.webp',
 'Care Credit - Charge Off1.docx',
 'Baines_Assign 1.pdf',
 'Intent to Withdraw Form - Tyrone Baines.pdf',
 'CIS 5090 Exam 3.docx',
 'OneDrive',
 'JB DL.pdf',
 'breast+cancer+wisconsin+diagnostic.zip',
 'Validation Request - Credit Control.docx',
 'Lakendra-Baines.pdf',
 'ARD Screenshot 3.jpg',
 'The Power of Big Data and Big Data Analytics.docx',
 '2025-vision-board-printable-original.png',
 'javac Card.js',
 '51ptB+yS0hL._AC_UF1000,1000_QL80_.jpg',
 'Untitled4.ipynb',
 'UAB Graduate School Essay.docx',
 'Capital One Goodwill Letter -1.docx',
 'IMG_6413.jpg',
 'Untitled13.ipynb',
 'Untitled56.ipynb',
 'LakendraBaines, MBA-HRM.pdf',
 'Sales Performance Dashboard.png',
 'Milestone 3.ipynb',
 'Bye Bye Bottle.pdf',
 'Untitled6.ipynb',
 'Return Documents.pdf',
 'Jerome Baines Jr Birth Certificate.pdf',
 'Pictures',
 'Cover Letter - Certification .docx',
 'Untitled11.ipynb',
 'DeckOfCardsTest.java',
 'CIS 5355 Assignment 2 .ipynb',
 'Resume & Cover Letter.docx',
 'Untitled54.ipynb',
 'Assignment 1 CIS 5304 .docx',
 'ARD Screenshot 1.jpg',
 'HW2.java',
 'Info_Assur_Security_MISY_5320_Fall_2023.pdf',
 'Validation Request - Credit Control.pdf',
 'ExportPractice.pdf',
 'Lakendra Baines -7.29.2025.pdf',
 'Jerome_Baines_Cover_Letter.pdf',
 'CIS 5355 Assignment 2.ipynb',
 'Jazlene Locander Resume .docx',
 'espedfile - revised ARD.pdf',
 'IMG_2059.jpg',
 'Jerome Baines Jr espedfile 5. 2025.pdf',
 '.zprofile',
 'Data Dictonary .docx',
 'q1_loan_type_purpose.png',
 'Lakendra B Passport.jpg',
 'Lakendra_Baines Resume1.pdf',
 'HR Data Analytics1 .ipynb',
 'Validation Request - Spire Recovery..docx',
 'CertificateOfCompletion_Reinforcement Learning Foundations.pdf',
 'Lakendra Baines .docx',
 'University of Houston Appeal.docx',
 'LakendraBaines, MBA-HRM.docx',
 'Untitled35.ipynb',
 'HR Data Analytics1.pdf',
 'i-9.pdf',
 'Info_Assur_Security_MISY_5320_Fall_2023 (1).pdf',
 'CertificateOfCompletion_Microsoft Power BI Data Analyst Associate PL300 Cert Prep by Microsoft Press.pdf',
 'CIS - 5090 Exam 1.docx',
 'espedfile Q1 Progress Report.pdf',
 'Method of Verification - Experian.docx',
 'Untitled49.ipynb',
 'Velveeta G. Recommendation.pdf',
 'HRIS-Functions-min.png',
 'A4LB.docx',
 'ARD Screenshot 4.jpg',
 'SST.pdf',
 'espedfile - Full ARD.pdf',
 'IMG_5918.PNG.pdf',
 'annotated-Literature%20Topic%20Submission%20.docx (1).pdf',
 'A8LB.docx',
 'Untitled31.ipynb',
 'Jazlene L. Resume.docx',
 '401k 11.8.2024.pdf',
 'Untitled Folder 2',
 'CertificateOfCompletion_Tableau 2024.1 Essential Training.pdf',
 'Kroger_Cashier_Cover_Letter.docx',
 'Untitled15.ipynb',
 'Untitled50.ipynb',
 'PayPal - Charge Off.docx',
 'IEP 2024-2025 .pdf',
 'com-3b3s-stacked.png',
 'CIS 5302 Assignment 2.docx',
 'Annual ARD Documents 11:6:25 J. Baines - signed.pdf',
 '.zsh_history',
 'CIS 5090 Comp Exam Part 5.docx',
 'Untitled2.ipynb',
 '.ipython',
 'txu 7:10:2025.pdf',
 'Baines_Assign3.ipynb',
 'CertificateOfCompletion_Program Databases with TransactSQL.pdf',
 'Desktop',
 'Technology Presentation.pptx',
 'espedfile Q2 Progress Report .pdf',
 'Final Project Report .pdf',
 'Library',
 'Production Planning 7.9.2023.xlsx',
 'Campus Dining Services Information System.docx',
 'Hospital Dashboard.twbx',
 'Percepta_Logo.jpg',
 'CoverLetter.docx',
 'Untitled28.ipynb',
 'Validation Request -  Firstsource.pdf',
 '.matplotlib',
 'Understanding the NIST Cybersecurity Framework Core.docx',
 'Homework 2 CIS 5353.docx',
 'Baines_Assign1.ipynb',
 'Annual Credit Report - Experian.pdf',
 'Validation Request - OneMain.docx',
 'espedfile - IEP.pdf',
 'Untitled-1.java',
 'Untitled Folder 3',
 'Developing Telecommunication Best Practices  .pptx',
 'Regional Finanace Goodwill Letter.docx',
 'Lakendra-Baines Cover Letter.pdf',
 'Websites Analytics.xlsx',
 'SAPAppeal Form.pdf',
 'bank-full.csv',
 'Untitled17.ipynb',
 'Untitled52.ipynb',
 'Jerome Baines Reference for Kendra.pdf',
 'il_300x300.4536074335_1nxt.avif',
 'Untitled33.ipynb',
 'thank-you-message.png',
 '.oracle_jre_usage',
 'Account.java',
 'CertificateOfCompletion_SQL for Data Analysis.pdf',
 'Infotmation Systems-LBaines.pdf',
 'Homework 2.docx',
 'System Analysis and Design - Mid Term.pdf',
 'AI.jpeg',
 'f12508 - Jerome Baines.pdf',
 'Final Project Report.ipynb',
 'Cover Letter _.docx',
 'Ashley Price _ “Write the vision and make it plain” Habakkuk 2_2-3 🙌🏾✨ Habakkuk 2_2-3 emphasizes the importance of writing down your vision and plans so... _ Instagram.html',
 'Form 8857.pdf',
 '1689900685-franchise-crew-application-210507.pdf',
 'TAMUCT.png',
 'ARD Screenshot 5_files',
 'Validation Request - Spire Recovery .docx',
 'Untitled47.ipynb',
 'README.md',
 'HR Dashboard.twb',
 'Dashboardtemplate.xltx',
 'HR Data Analytics .ipynb',
 'P10_16 6.26.2023.xlsx',
 'Validation Request - Phillips & Cohen.pdf',
 'covid_vaccinations_bokeh.ipynb',
 'Tyrone Baines Progress Report.pdf',
 'Form E - August 2026 .pdf',
 'Office Services.pdf',
 '.pgadmin',
 'Sales Force.docx',
 'ARD Screenshot 16',
 'Preparing a Report Based on the NIST Special Publications.docx',
 '.cups',
 'Chantavia Baines Resume.pdf',
 'ARD Screenshot 7',
 'new_finance.csv',
 'DataDictionary.xlsx',
 'Technology Presentation1.pptx',
 'LB Resume1.pdf',
 'results',
 'A10LB.docx',
 'sales_data.xlsx',
 'ARD Screenshot 11',
 'ARD Screenshot 9',
 'CertificateOfCompletion_Wireshark Essential Training.pdf',
 'Pay off Matrix.xlsx',
 'ARD Screenshot 18',
 'Lakendra Baines Resume.docx',
 'Edgewood University .pdf',
 'Validation Request - Paramount Recovery.docx',
 'logistic_regression .R',
 'Untitled63.ipynb',
 'Untitled26.ipynb',
 'taxi_zone_lookup.csv',
 'Jerome Baines Jr.pdf',
 'IMG_4804.pdf',
 'untitled.txt',
 'ARD Screenshot 20',
 'Invoices .xlsx',
 'Debt Validation - Midland Services 7.25.2023.docx',
 'Breakeven Analysis.xlsx',
 'diabetic_data.csv',
 'MyChart - Jerome Jr Immunizations.pdf',
 'Assignment 2 CIS 5304.docx',
 'Validation Request - AssetCare .docx',
 'SAS 2.docx',
 'Velveeta G. Recommendation.docx',
 'Project Phase 1.docx',
 'Untitled61.ipynb',
 '.~HR Dashboard__394.twbr',
 'Untitled24.ipynb',
 'Michelle BainesResume.docx',
 'CIS 5355 Assignment 2 Python.ipynb',
 'Answer Template-PS 10.8.2023.docx',
 'Untitled19.ipynb',
 'IMG_4804.jpg',
 'Final Exam.ipynb',
 '~$Technology Presentation.pptx',
 'Revision Annual ARD 1.15.2025 .pdf',
 'A1LB.docx',
 'Public',
 'Lakendra Baines - Cover Letter.docx',
 'Academic Transcript - Unofficial.pdf',
 'QuantityPrediction.xlsx',
 '2015-02-07-3ecf9d9f8f71c9fd0dea1d0f2a6ce610.jpg',
 'best-careers-for-remote-work-anomadic-825x510.jpg',
 '2025-GLE-SUV-CT-1-5-01-DR.webp',
 'Student Enrollment System .docx',
 'Jerome Baines Withdrawal Transfer Form.pdf',
 'CIS 5355 Final Exam 12.8.2025.ipynb',
 'ARD Screenshot 21',
 'ARD Screenshot 19',
 'Enterprise_Sys_CRM_MISY_5380_Spring_2024 (2).pdf',
 'Motor Vehicle Driver’s Certification.pdf',
 'ARD Screenshot 8',
 'new_finance_.csv',
 'Jerome Time Sheet 7.15.2024.pdf',
 'CIS 5355 Assignment 4.pdf',
 'HW2 11.19.2025.java',
 'IMG_8837 4.pdf',
 'ARD Screenshot 10',
 'State Diagram.pdf',
 'Untitled45.ipynb',
 'State Machine Diagram.pdf',
 'EmployeeTest.class',
 'Finance_data.csv',
 'ARD Screenshot 17',
 'Developing an Email Classification System and Handling Standards.docx',
 'untitled.r',
 'untitled1.txt',
 'Untitled39.ipynb',
 'CIS 5357 Final Project Report .docx',
 '.tcshrc',
 'A3LB.docx',
 'Assignment 1 CIS 5304.docx',
 'Hw1Project2.class',
 '.vscode-R',
 'Banking Loan.sql',
 'Individual Project - Healthcare Analytics.docx',
 'Untitled41.ipynb',
 'Creating Incident Awareness Training.pptx',
 'CertificateOfCompletion_Python Essential Training.pdf',
 'University of Houston Appeal.pdf',
 'house_price_lm_summary.R',
 'DATA (1).csv',
 'IT Project Management Plan.pdf',
 'Birth CertificateJB.pdf',
 'Lakendra Baines.docx',
 'Untitled65.ipynb',
 'Untitled20.ipynb',
 'AI-text-to-image-photo-robot-with-computer.webp',
 'POA - Jazlene Locander.pdf',
 'EPT89.webp',
 '.virtual_documents',
 'Capital One Goodwill Letter.docx',
 'writing-perfect-thank-you-post.webp',
 'Experian - Inquiry .docx',
 'Maospalace.xlsx',
 'Regression & Forecasting.docx',
 'scripts',
 'Tyrone Birth Certificate .jpg',
 'Project Phase 4.pdf',
 'LakendraBaines, MBA-HRM - Certification.docx',
 '.anaconda',
 'creditReport_4530598870 - Exquifax.pdf',
 'AdobeStock_157266517-1200x640.webp',
 'Employee.class',
 'Lakendra Baines Passport .jpg',
 'Baines_Assign3.pdf',
 'Untitled58.ipynb',
 'Baines_Assign1.pdf',
 'Tyrone SS Card.jpg',
 'Lakendra Baines --.docx',
 'Untitled8.ipynb',
 'Leading Cause of Death.docx',
 'Interview Questions.pdf',
 'Merrick Bank Corp - Charge Off.docx',
 'CertificateOfCompletion_Learning Excel Data Analysis (1).pdf',
 'P02_10 - June 24. 2023.xlsx',
 'Movies',
 'UAB Graduate School Essay.pdf',
 'Jerome Baines Documents - Pearland Urology.pdf',
 'Hospital Reporting Data.xls',
 'Applications',
 'ExportPractice.xlsx',
 'Validation Request -  Firstsource.docx',
 'Untitled67.ipynb',
 'Untitled22.ipynb',
 'CertificateOfCompletion_Excel Managing and Analyzing Data.pdf',
 'LakendraB .pdf',
 'MEDLINE_master_table.csv',
 'Lakendra_Baines_HRIS_Resume.docx',
 'Answer Sheet - Analysis Using GBI Pt1.docx',
 'Untitled43.ipynb',
 'Google China (2009).docx',
 '~$S 5357 Final Project Report .docx',
 'magic+gamma+telescope.zip',
 '~$Transportation 7.16.2023.xlsx',
 '24E6DC6B-4FD9-4A29-A704-08CD56773599.webp',
 'IRS Form 8857.pdf',
 '.Rapp.history',
 'Transportation 7.16.2023.xlsx',
 'espedfile 1:2025 Revised ARD.pdf',
 'HR Dashboard.twbx',
 'Tyrone Baines Resume .docx',
 'espedfile last progress report.pdf',
 'Lamar University .pdf',
 '.~Sales Performance Dashboard__74769.twbr',
 'LoanApplications (2).xlsx',
 'Conns Goodwill Letter.docx',
 '.Trash',
 'IMG_8837 2.pdf',
 'GB_AnalyticsData .xlsx',
 'MISY 5370 Final Exam - Lakendra Baines.docx',
 'Power Point.docx',
 'HW2.js',
 '.ipynb_checkpoints',
 'Untitled18.ipynb',
 'School Learning.xls',
 'State Machine Diagram .docx',
 '~$Homework 2 CIS 5353.xlsx',
 'Final Exam.pdf',
 'DefendantsAnswer.pdf',
 'lakendrabaines.ipynb',
 '.jupyter',
 'Debt Validation - True Accord 10.2.2023.docx',
 'Untitled25.ipynb',
 'Untitled60.ipynb',
 'hr_analytics_queries.sql',
 'Answer Template-PP 9.17.2023.docx',
 'Individual Project.ipynb',
 'HW1.code-workspace',
 'Method of Verification Letter.docx',
 'Untitled44.ipynb',
 'Terminal Saved Output.txt',
 'Account.class',
 'SalesDB_Analysis_Portfolio.ipynb',
 'FlighttoSeattle.pdf',
 'Validation Request - Midland Credit .docx',
 'Cybersecurity_Man_MISY_5325_Fall_2023 (1).pdf',
 'JB Report Card 1 2023-2024.pdf',
 'Documents',
 'Lakendra Baines Social Security .jpg',
 'Validation Request - Portfolio Recoery.pdf',
 'Personal Statement.docx',
 'Developing Communicating and Training Skills.pptx',
 'A7LB.docx',
 'School Learning Modalities 7.2.2023.docx',
 'CIS 5090 Comp Exam 2.docx',
 '~$am 2 CIS 5353.docx',
 'Chantavia-Baines.pdf',
 'Wells-Fargo_Moral-Emotions-Case-Study_English.pdf',
 '.rstudio-desktop',
 'Transportation 7.16.xlsx',
 'LInkedIn Banner.png',
 'My Percepta Presentation.pptx',
 'Untitled46.ipynb',
 'Data.xls',
 '.vscode',
 'Validation Request - Credit Control..docx',
 'Information Systems - Lakendra Baines.pdf',
 'Product Mix 1 7.9.2023.xlsx',
 'thumbnail.jpeg',
 'Untitled27.ipynb',
 'Untitled62.ipynb',
 'Mile Stone1.pdf',
 'Letter of Recommendation - Holly Hall.pdf',
 'Benfords percents.xlsx',
 '.bash_profile',
 'Hospital Financial Analysis.docx',
 'Milestone 3.pdf',
 'EmployeeTest.java',
 'HR Dashboard.pdf',
 'Heavenly Chocolates .docx',
 'Always .pdf',
 '~$CIS 5353 Homework 1.xlsx',
 'DPS Audit Verification 092015 Rev 2.pdf',
 'Literature Topic Submission .docx',
 'Healthcare.sql',
 'Lakendra Baines -.pdf',
 'CIS 5353 Homework 1.xlsx',
 'database 2.csv',
 'CIS 5355 - Final Exam Discussion Questions.docx',
 'Downloads',
 '.python_history',
 '.redhat',
 'E-File .pdf',
 'Untitled23.ipynb',
 '.continuum',
 'Untitled66.ipynb',
 'LakendraBaines, MBA-HRM - SQL Certification.docx',
 'Salesforce Assignment.docx',
 'Student_Success_Analysis.ipynb.ipynb',
 'Jerome Baines CDL A.jpg',
 'L20593228 GPA.pdf',
 'Validation Request - Resurgent Capital Services.docx',
 'Elektra Carter.pdf',
 'Transunion - Inquiry .docx',
 'SAPAppealApplication.pdf',
 'The-Costco-Model (1).pdf',
 'Untitled9.ipynb',
 'banking.db',
 'LB Resume.docx',
 'Hw1Project1.class',
 'analysis.ipynb',
 'Information Systems - Lakendra Baines_compressed.pdf',
 'Creating Incident Awareness Training.docx',
 'f12508.pdf',
 'Mid term.pdf',
 'Jertoria & Tyrone Withdrawal Forms.pdf',
 'Untitled Folder 1',
 'adidas_usa 7.10.2026.xlsx',
 'Untitled42.ipynb',
 'artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled.jpg',
 'World Finance Corp - Charge Off.docx',
 'CIS 5304 Assignment 3.pdf',
 'Jerome DL.HEIC',
 '.zsh_sessions',
 '~$chnology Report.docx',
 'ERPSim Game Questions 10.1.2023.docx',
 'Lakendra-Baines-Human Resources  (1).pdf',
 'covid_vaccinations_scatter.html',
 'Workforce Attrition Analytics Dashboard.twb',
 'wdbc.data',
 'Untitled40.ipynb',
 'Untitled38.ipynb',
 'HW2 11.19.2025..java',
 'Validation Request -  South District Group.docx',
 'GettyImages-1030831244-4279d87f1272423288e24a9ed9925c80.webp',

In [8]:
import os

for location in ["Desktop", "Documents", "Downloads"]:
    path = os.path.join(os.path.expanduser("~"), location)
    if os.path.exists(path):
        matches = [x for x in os.listdir(path) if "student" in x.lower()]
        print(location, matches)

Desktop ['student-success-analytics']
Documents ['student-mat.csv']
Downloads ['predict+students+dropout+and+academic+success (1).zip', 'student_data.csv', 'High_School_Student_Resume.docx', 'SocialSkillsPrintablesforStudentswithAutismSimilarSpecialNeeds-1.pdf', 'higher+education+students+performance+evaluation.zip', 'predict+students+dropout+and+academic+success.zip', 'student+performance', 'student+performance.zip', 'Student_Enrollment_System_References.docx']

In [10]:
df = pd.read_csv(
    "Desktop/student-success-analytics/Data/student_success_raw.csv",
    sep=";"
)

df.shape

(4424, 37)

In [12]:
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance	                     4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4424 non-null   int64
 10  Mother's occupation                             4424 non-null   int64
 11  Father's occupation                             4424 non-null   int64
 12  Admission grade                                 4424 non-null   float64
 13  Displaced                                       4424 non-null   int64
 14  Educational special needs                       4424 non-null   int64
 15  Debtor                                          4424 non-null   int64
 16  Tuition fees up to date                         4424 non-null   int64
 17  Gender                                          4424 non-null   int64
 18  Scholarship holder                              4424 non-null   int64
 19  Age at enrollment                               4424 non-null   int64
 20  International                                   4424 non-null   int64
 21  Curricular units 1st sem (credited)             4424 non-null   int64
 22  Curricular units 1st sem (enrolled)             4424 non-null   int64
 23  Curricular units 1st sem (evaluations)          4424 non-null   int64
 24  Curricular units 1st sem (approved)             4424 non-null   int64
 25  Curricular units 1st sem (grade)                4424 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 27  Curricular units 2nd sem (credited)             4424 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 29  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 30  Curricular units 2nd sem (approved)             4424 non-null   int64
 31  Curricular units 2nd sem (grade)                4424 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 33  Unemployment rate                               4424 non-null   float64
 34  Inflation rate                                  4424 non-null   float64
 35  GDP                                             4424 non-null   float64
 36  Target                                          4424 non-null   object
dtypes: float64(7), int64(29), object(1)
memory usage: 1.2+ MB

In [16]:
df.isnull().sum()

Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance\t                      0
Previous qualification                            0
Previous qualification (grade)                    0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Admission grade                                   0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 0
International                                     0
Curricular units 1st sem (credited)               0
Curricular units 1st sem (enrolled)               0
Curricular units 1st sem (evaluations)            0
Curricular units 1st sem (approved)               0
Curricular units 1st sem (grade)                  0
Curricular units 1st sem (without evaluations)    0
Curricular units 2nd sem (credited)               0
Curricular units 2nd sem (enrolled)               0
Curricular units 2nd sem (evaluations)            0
Curricular units 2nd sem (approved)               0
Curricular units 2nd sem (grade)                  0
Curricular units 2nd sem (without evaluations)    0
Unemployment rate                                 0
Inflation rate                                    0
GDP                                               0
Target                                            0
dtype: int64

In [18]:
df.duplicated().sum()

0

In [20]:
df['Target'].value_counts()

Graduate    2209
Dropout     1421
Enrolled     794
Name: Target, dtype: int64

In [22]:
df['Target'].value_counts(normalize=True) * 100

Graduate    49.932188
Dropout     32.120253
Enrolled    17.947559
Name: Target, dtype: float64

In [24]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r'[^\w]+', '_', regex=True)
    .str.strip('_')
)

df.columns.tolist()

['marital_status',
 'application_mode',
 'application_order',
 'course',
 'daytime_evening_attendance',
 'previous_qualification',
 'previous_qualification_grade',
 'nacionality',
 'mother_s_qualification',
 'father_s_qualification',
 'mother_s_occupation',
 'father_s_occupation',
 'admission_grade',
 'displaced',
 'educational_special_needs',
 'debtor',
 'tuition_fees_up_to_date',
 'gender',
 'scholarship_holder',
 'age_at_enrollment',
 'international',
 'curricular_units_1st_sem_credited',
 'curricular_units_1st_sem_enrolled',
 'curricular_units_1st_sem_evaluations',
 'curricular_units_1st_sem_approved',
 'curricular_units_1st_sem_grade',
 'curricular_units_1st_sem_without_evaluations',
 'curricular_units_2nd_sem_credited',
 'curricular_units_2nd_sem_enrolled',
 'curricular_units_2nd_sem_evaluations',
 'curricular_units_2nd_sem_approved',
 'curricular_units_2nd_sem_grade',
 'curricular_units_2nd_sem_without_evaluations',
 'unemployment_rate',
 'inflation_rate',
 'gdp',
 'target']

In [26]:
coded_columns = [
    'marital_status',
    'application_mode',
    'course',
    'daytime_evening_attendance',
    'previous_qualification',
    'nationality',
    'displaced',
    'educational_special_needs',
    'debtor',
    'tuition_fees_up_to_date',
    'gender',
    'scholarship_holder',
    'international'
]

for col in coded_columns:
    print(f"\n{col}")
    print(df[col].value_counts().sort_index())

marital_status
1    3919
2     379
3       4
4      91
5      25
6       6
Name: marital_status, dtype: int64

application_mode
1     1708
2        3
5       16
7      139
10      10
15      30
16      38
17     872
18     124
26       1
27       1
39     785
42      77
43     312
44     213
51      59
53      35
57       1
Name: application_mode, dtype: int64

course
33       12
171     215
8014    215
9003    210
9070    226
9085    337
9119    170
9130    141
9147    380
9238    355
9254    252
9500    766
9556     86
9670    268
9773    331
9853    192
9991    268
Name: course, dtype: int64

daytime_evening_attendance
0     483
1    3941
Name: daytime_evening_attendance, dtype: int64

previous_qualification
1     3717
2       23
3      126
4        8
5        1
6       16
9       11
10       4
12      45
14       1
15       2
19     162
38       7
39     219
40      40
42      36
43       6
Name: previous_qualification, dtype: int64

nationality

KeyError: 'nationality'

In [28]:
binary_columns = [
    'displaced',
    'educational_special_needs',
    'debtor',
    'tuition_fees_up_to_date',
    'gender',
    'scholarship_holder',
    'international'
]

for col in binary_columns:
    print(f"\n{col}")
    print(df[col].value_counts().sort_index())

displaced
0    1998
1    2426
Name: displaced, dtype: int64

educational_special_needs
0    4373
1      51
Name: educational_special_needs, dtype: int64

debtor
0    3921
1     503
Name: debtor, dtype: int64

tuition_fees_up_to_date
0     528
1    3896
Name: tuition_fees_up_to_date, dtype: int64

gender
0    2868
1    1556
Name: gender, dtype: int64

scholarship_holder
0    3325
1    1099
Name: scholarship_holder, dtype: int64

international
0    4314
1     110
Name: international, dtype: int64

In [30]:
yes_no_columns = [
    'displaced',
    'educational_special_needs',
    'debtor',
    'tuition_fees_up_to_date',
    'scholarship_holder',
    'international'
]

for col in yes_no_columns:
    df[col] = df[col].map({0: 'No', 1: 'Yes'})

df[yes_no_columns].head()

,displaced,educational_special_needs,debtor,tuition_fees_up_to_date,scholarship_holder,international
0,Yes,No,No,Yes,No,No
1,Yes,No,No,No,No,No
2,Yes,No,No,No,No,No
3,Yes,No,No,Yes,No,No
4,No,No,No,Yes,No,No

In [32]:
df.to_csv(
    "Desktop/student-success-analytics/Data/student_success_cleaned.csv",
    index=False
)

In [34]:
import os

os.path.exists(
    "Desktop/student-success-analytics/Data/student_success_cleaned.csv"
)

True

In [36]:
marital_status_map = {
    1: 'Single',
    2: 'Married',
    3: 'Widower',
    4: 'Divorced',
    5: 'Facto Union',
    6: 'Legally Separated'
}

df['marital_status'] = df['marital_status'].map(marital_status_map)

df['marital_status'].value_counts()

Single               3919
Married               379
Divorced               91
Facto Union            25
Legally Separated       6
Widower                 4
Name: marital_status, dtype: int64

In [38]:
df['application_mode'].value_counts().sort_index()

1     1708
2        3
5       16
7      139
10      10
15      30
16      38
17     872
18     124
26       1
27       1
39     785
42      77
43     312
44     213
51      59
53      35
57       1
Name: application_mode, dtype: int64

In [40]:
application_mode_map = {
    1: '1st Phase - General Contingent',
    2: 'Ordinance No. 612/93',
    5: '1st Phase - Special Contingent (Azores)',
    7: 'Holders of Other Higher Courses',
    10: 'Ordinance No. 854-B/99',
    15: 'International Student (Bachelor)',
    16: '1st Phase - Special Contingent (Madeira)',
    17: '2nd Phase - General Contingent',
    18: '3rd Phase - General Contingent',
    26: 'Ordinance No. 533-A/99 - Different Plan',
    27: 'Ordinance No. 533-A/99 - Other Institution',
    39: 'Over 23 Years Old',
    42: 'Transfer',
    43: 'Change of Course',
    44: 'Technological Specialization Diploma',
    51: 'Change of Institution/Course',
    53: 'Short Cycle Diploma',
    57: 'Change of Institution/Course (International)'
}

df['application_mode'] = df['application_mode'].map(application_mode_map)

df['application_mode'].value_counts()

1st Phase - General Contingent                  1708
2nd Phase - General Contingent                   872
Over 23 Years Old                                785
Change of Course                                 312
Technological Specialization Diploma             213
Holders of Other Higher Courses                  139
3rd Phase - General Contingent                   124
Transfer                                          77
Change of Institution/Course                      59
1st Phase - Special Contingent (Madeira)          38
Short Cycle Diploma                               35
International Student (Bachelor)                  30
1st Phase - Special Contingent (Azores)           16
Ordinance No. 854-B/99                            10
Ordinance No. 612/93                               3
Change of Institution/Course (International)       1
Ordinance No. 533-A/99 - Different Plan            1
Ordinance No. 533-A/99 - Other Institution         1
Name: application_mode, dtype: int64

In [42]:
df['course'].value_counts().sort_index()

33       12
171     215
8014    215
9003    210
9070    226
9085    337
9119    170
9130    141
9147    380
9238    355
9254    252
9500    766
9556     86
9670    268
9773    331
9853    192
9991    268
Name: course, dtype: int64

In [44]:
course_map = {
    33: 'Biofuel Production Technologies',
    171: 'Animation and Multimedia Design',
    8014: 'Social Service (Evening)',
    9003: 'Agronomy',
    9070: 'Communication Design',
    9085: 'Veterinary Nursing',
    9119: 'Informatics Engineering',
    9130: 'Equinculture',
    9147: 'Management',
    9238: 'Social Service',
    9254: 'Tourism',
    9500: 'Nursing',
    9556: 'Oral Hygiene',
    9670: 'Advertising and Marketing Management',
    9773: 'Journalism and Communication',
    9853: 'Basic Education',
    9991: 'Management (Evening)'
}

df['course'] = df['course'].map(course_map)

df['course'].value_counts()

Nursing                                 766
Management                              380
Social Service                          355
Veterinary Nursing                      337
Journalism and Communication            331
Advertising and Marketing Management    268
Management (Evening)                    268
Tourism                                 252
Communication Design                    226
Animation and Multimedia Design         215
Social Service (Evening)                215
Agronomy                                210
Basic Education                         192
Informatics Engineering                 170
Equinculture                            141
Oral Hygiene                             86
Biofuel Production Technologies          12
Name: course, dtype: int64

In [46]:
attendance_map = {
    1: 'Daytime',
    0: 'Evening'
}

df['daytime_evening_attendance'] = (
    df['daytime_evening_attendance'].map(attendance_map)
)

df['daytime_evening_attendance'].value_counts()

Daytime    3941
Evening     483
Name: daytime_evening_attendance, dtype: int64

In [48]:
df['previous_qualification'].value_counts().sort_index()

1     3717
2       23
3      126
4        8
5        1
6       16
9       11
10       4
12      45
14       1
15       2
19     162
38       7
39     219
40      40
42      36
43       6
Name: previous_qualification, dtype: int64

In [50]:
previous_qualification_map = {
    1: 'Secondary Education',
    2: "Higher Education - Bachelor's Degree",
    3: 'Higher Education - Degree',
    4: "Higher Education - Master's",
    5: 'Higher Education - Doctorate',
    6: 'Frequency of Higher Education',
    9: '12th Year - Not Completed',
    10: '11th Year - Not Completed',
    12: 'Other - 11th Year',
    14: '10th Year',
    15: '10th Year - Not Completed',
    19: 'Basic Education - 3rd Cycle',
    38: 'Basic Education - 2nd Cycle',
    39: 'Technological Specialization Course',
    40: 'Higher Education - Degree (1st Cycle)',
    42: 'Professional Higher Technical Course',
    43: 'Higher Education - Master (2nd Cycle)'
}

df['previous_qualification'] = (
    df['previous_qualification'].map(previous_qualification_map)
)

df['previous_qualification'].value_counts()

Secondary Education                      3717
Technological Specialization Course       219
Basic Education - 3rd Cycle               162
Higher Education - Degree                 126
Other - 11th Year                          45
Higher Education - Degree (1st Cycle)      40
Professional Higher Technical Course       36
Higher Education - Bachelor's Degree       23
Frequency of Higher Education              16
12th Year - Not Completed                  11
Higher Education - Master's                 8
Basic Education - 2nd Cycle                 7
Higher Education - Master (2nd Cycle)       6
11th Year - Not Completed                   4
10th Year - Not Completed                   2
Higher Education - Doctorate                1
10th Year                                   1
Name: previous_qualification, dtype: int64

In [52]:
gender_map = {
    0: 'Female',
    1: 'Male'
}

df['gender'] = df['gender'].map(gender_map)

df['gender'].value_counts()

Female    2868
Male      1556
Name: gender, dtype: int64

In [54]:
df['nationality'].value_counts().sort_index()

KeyError: 'nationality'

In [56]:
df = df.rename(columns={
    'nacionality': 'nationality'
})

df['nationality'].value_counts().sort_index()

1      4314
2         2
6        13
11        3
13        1
14        1
17        1
21        2
22       13
24        5
25        2
26       14
32        1
41       38
62        2
100       3
101       2
103       3
105       2
108       1
109       1
Name: nationality, dtype: int64

In [58]:
df['age_group'] = pd.cut(
    df['age_at_enrollment'],
    bins=[0, 20, 25, 30, 40, 100],
    labels=['20 and Under', '21-25', '26-30', '31-40', '41+']
)

df['age_group'].value_counts().sort_index()

20 and Under    2551
21-25            828
26-30            383
31-40            437
41+              225
Name: age_group, dtype: int64

In [60]:
df['first_sem_approval_rate'] = np.where(
    df['curricular_units_1st_sem_enrolled'] > 0,
    df['curricular_units_1st_sem_approved'] /
    df['curricular_units_1st_sem_enrolled'],
    np.nan
)

df['second_sem_approval_rate'] = np.where(
    df['curricular_units_2nd_sem_enrolled'] > 0,
    df['curricular_units_2nd_sem_approved'] /
    df['curricular_units_2nd_sem_enrolled'],
    np.nan
)

df[
    ['first_sem_approval_rate', 'second_sem_approval_rate']
].describe()

       first_sem_approval_rate  second_sem_approval_rate
count              4244.000000               4244.000000
mean                  0.727484                  0.688364
std                   0.342821                  0.365513
min                   0.000000                  0.000000
25%                   0.600000                  0.500000
50%                   0.857143                  0.833333
75%                   1.000000                  1.000000
max                   1.000000                  1.000000

In [62]:
approval_by_outcome = (
    df.groupby('target', observed=True)[
        ['first_sem_approval_rate', 'second_sem_approval_rate']
    ]
    .mean()
    .round(3)
)

approval_by_outcome

          first_sem_approval_rate  second_sem_approval_rate
target
Dropout                     0.406                     0.310
Enrolled                    0.714                     0.673
Graduate                    0.935                     0.932

In [64]:
df['dropout_flag'] = (df['target'] == 'Dropout').astype(int)
df['graduate_flag'] = (df['target'] == 'Graduate').astype(int)

df[

    ['target', 'dropout_flag', 'graduate_flag']
].head(10)

     target  dropout_flag  graduate_flag
0   Dropout             1              0
1  Graduate             0              1
2   Dropout             1              0
3  Graduate             0              1
4  Graduate             0              1
5  Graduate             0              1
6  Graduate             0              1
7   Dropout             1              0
8  Graduate             0              1
9   Dropout             1              0

In [66]:
print("Dataset shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())
print("Total missing values:", df.isnull().sum().sum())

print("\nTarget counts:")
print(df['target'].value_counts())

print("\nDropout flag total:", df['dropout_flag'].sum())
print("Graduate flag total:", df['graduate_flag'].sum())

print("\nFinal columns:")
print(df.columns.tolist())

Dataset shape: (4424, 42)
Duplicate rows: 0
Total missing values: 360

Target counts:
Graduate    2209
Dropout     1421
Enrolled     794
Name: target, dtype: int64

Dropout flag total: 1421
Graduate flag total: 2209

Final columns:
['marital_status', 'application_mode', 'application_order', 'course', 'daytime_evening_attendance', 'previous_qualification', 'previous_qualification_grade', 'nationality', 'mother_s_qualification', 'father_s_qualification', 'mother_s_occupation', 'father_s_occupation', 'admission_grade', 'displaced', 'educational_special_needs', 'debtor', 'tuition_fees_up_to_date', 'gender', 'scholarship_holder', 'age_at_enrollment', 'international', 'curricular_units_1st_sem_credited', 'curricular_units_1st_sem_enrolled', 'curricular_units_1st_sem_evaluations', 'curricular_units_1st_sem_approved', 'curricular_units_1st_sem_grade', 'curricular_units_1st_sem_without_evaluations', 'curricular_units_2nd_sem_credited', 'curricular_units_2nd_sem_enrolled', 'curricular_units_2nd_sem_evaluations', 'curricular_units_2nd_sem_approved', 'curricular_units_2nd_sem_grade', 'curricular_units_2nd_sem_without_evaluations', 'unemployment_rate', 'inflation_rate', 'gdp', 'target', 'age_group', 'first_sem_approval_rate', 'second_sem_approval_rate', 'dropout_flag', 'graduate_flag']

In [68]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0].sort_values(ascending=False)

first_sem_approval_rate     180
second_sem_approval_rate    180
dtype: int64

In [70]:
df.to_csv(
    "Desktop/student-success-analytics/Data/student_success_cleaned.csv",
    index=False
)

print("Final cleaned dataset saved!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Final cleaned dataset saved!
Rows: 4424
Columns: 42